### ISSUE TITLE
basic Mailing service

### ISSUE THREAD

**Issue by DrunkenToast** [tm-pe2/ad-api#2]
- [x] - email test account
- [x] - base class (variables from env?)
- [x] - basic functions
- [x] - email formatter?

**Comment by PandaGamersHDNL** [comment]
[ethereal](https://ethereal.email) seems better

**Comment by PandaGamersHDNL** [comment]
add unit testing

**Comment by PandaGamersHDNL** [comment]
closed for sprint 1
